# -*- coding: utf-8 -*-
"""Copy of Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Noxa2zjH19gzwjK8jAHvg9kEwyzGGDal
"""

from google.colab import files

uploaded = files.upload()

!pip install scikit-learn pandas numpy joblib --quiet
print("✅ Done")

import pandas as pd
import numpy as np
import joblib
import os
import warnings
warnings.filterwarnings("ignore")

from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, f1_score, accuracy_score

print("✅ All imports successful")

from google.colab import files
import io

print("📂 Click 'Choose Files' and upload HeartRate_Cleaned.csv")
uploaded = files.upload()

csv_filename = list(uploaded.keys())[0]
df = pd.read_csv(io.BytesIO(uploaded[csv_filename]))

print(f"✅ Loaded: {df.shape[0]} rows × {df.shape[1]} columns")
print("Columns:", list(df.columns))
df.head(3)

def assign_risk(row):
    score = 0
    if row['heart_rate'] > 100 or row['heart_rate'] < 50:
        score += 2
    if row['spo2_level'] < 94:
        score += 2
    if row['blood_pressure_sys'] > 140 or row['blood_pressure_sys'] < 90:
        score += 2
    if row['blood_glucose'] > 180 or row['blood_glucose'] < 70:
        score += 1
    if row['body_temperature'] > 38.0 or row['body_temperature'] < 35.5:
        score += 1
    if row['respiration_rate'] > 20 or row['respiration_rate'] < 10:
        score += 1
    if row['fall_detected'] == 1:
        score += 2
    if row['stress_level_index'] > 70:
        score += 1

    if score <= 1:
        return 'Low'
    elif score <= 4:
        return 'Medium'
    else:
        return 'High'

df['risk_level'] = df.apply(assign_risk, axis=1)

print("✅ Risk column created")
print(df['risk_level'].value_counts())

FEATURE_COLS = [
    'heart_rate', 'spo2_level', 'ecg_signal', 'respiration_rate',
    'body_temperature', 'blood_pressure_sys', 'blood_pressure_dia',
    'blood_glucose', 'eeg_alpha_power', 'eeg_beta_power',
    'emg_signal_strength', 'fall_detected', 'step_count',
    'ambient_temperature', 'stress_level_index', 'activity_type'
]

activity_encoder = LabelEncoder()
df['activity_type'] = activity_encoder.fit_transform(df['activity_type'])

X = df[FEATURE_COLS]
y = df['risk_level']

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("✅ Classes:", label_encoder.classes_)
print("✅ Features:", len(FEATURE_COLS))

X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled  = scaler.transform(X_test)

print(f"✅ Train: {X_train.shape[0]} rows | Test: {X_test.shape[0]} rows")

final_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=12,
    min_samples_split=4,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1
)

final_model.fit(X_train_scaled, y_train)

y_pred = final_model.predict(X_test_scaled)
acc = accuracy_score(y_test, y_pred)
f1  = f1_score(y_test, y_pred, average='weighted')
cv  = cross_val_score(final_model, X_train_scaled, y_train, cv=5, scoring='f1_weighted')

print(f"✅ Accuracy : {acc:.3f}")
print(f"✅ F1-Score : {f1:.3f}")
print(f"✅ CV Mean  : {cv.mean():.3f} ± {cv.std():.3f}")
print()

# ✅ FIX: Use only the classes actually present in y_test
import numpy as np
classes_in_test = np.unique(y_test)
class_names_in_test = label_encoder.inverse_transform(classes_in_test)

print(classification_report(y_test, y_pred,
                             labels=classes_in_test,
                             target_names=class_names_in_test))

feature_importances = dict(zip(FEATURE_COLS, final_model.feature_importances_))
TOP_FEATURES = sorted(feature_importances, key=feature_importances.get, reverse=True)[:3]
print("🏆 Top 3 features:", TOP_FEATURES)

os.makedirs("models", exist_ok=True)

joblib.dump(final_model,      "models/final_model.pkl")
joblib.dump(scaler,           "models/scaler.pkl")
joblib.dump(label_encoder,    "models/label_encoder.pkl")
joblib.dump(activity_encoder, "models/activity_encoder.pkl")
joblib.dump(FEATURE_COLS,     "models/feature_columns.pkl")
joblib.dump(TOP_FEATURES,     "models/top_features.pkl")

print("✅ All PKL files saved:")
for f in os.listdir("models"):
    size = os.path.getsize(f"models/{f}")
    print(f"   📦 {f}  ({size:,} bytes)")

loaded_model    = joblib.load("models/final_model.pkl")
loaded_scaler   = joblib.load("models/scaler.pkl")
loaded_encoder  = joblib.load("models/label_encoder.pkl")
loaded_act_enc  = joblib.load("models/activity_encoder.pkl")
loaded_features = joblib.load("models/feature_columns.pkl")
loaded_top_f    = joblib.load("models/top_features.pkl")

print("✅ All files load without errors!")
print("Feature columns:", loaded_features)
print("Label classes  :", loaded_encoder.classes_)
print("Activity classes:", loaded_act_enc.classes_)

print("""
==================================================
✅ FLASK HANDOFF CHECKLIST — Track 3
==================================================

PKL FILES:
  final_model.pkl       → Trained RandomForestClassifier (200 trees)
  scaler.pkl            → StandardScaler (fitted on 16 features)
  label_encoder.pkl     → Encodes Low / Medium / High
  activity_encoder.pkl  → Encodes walking/running/resting/sleeping
  feature_columns.pkl   → Ordered list of 16 input column names
  top_features.pkl      → Top 3 important features for display

INPUT COLUMNS (in order):
  heart_rate, spo2_level, ecg_signal, respiration_rate,
  body_temperature, blood_pressure_sys, blood_pressure_dia,
  blood_glucose, eeg_alpha_power, eeg_beta_power,
  emg_signal_strength, fall_detected, step_count,
  ambient_temperature, stress_level_index, activity_type

activity_type must be one of:
  resting | running | sleeping | walking

EXPECTED OUTPUT FORMAT:
  {
    'prediction' : 'Low',
    'confidence' : '84.7%',
    'top_features': ['heart_rate', 'spo2_level', 'blood_pressure_sys'],
    'risk_level'  : 'Low'
  }
==================================================
""")

def predict(input_dict):
    import pandas as pd
    import joblib

    # STEP 1 — Load all pkl files inside function
    try:
        model          = joblib.load("models/final_model.pkl")
        scaler         = joblib.load("models/scaler.pkl")
        label_enc      = joblib.load("models/label_encoder.pkl")
        activity_enc   = joblib.load("models/activity_encoder.pkl")
        feature_cols   = joblib.load("models/feature_columns.pkl")
        top_features   = joblib.load("models/top_features.pkl")
    except Exception as e:
        return {"error": f"Failed to load model files: {str(e)}"}

    # STEP 2 — Validate inputs
    for field in feature_cols:
        if field not in input_dict:
            return {"error": f"Missing field: '{field}'"}

    if input_dict.get('activity_type') not in list(activity_enc.classes_):
        return {"error": f"activity_type must be one of {list(activity_enc.classes_)}"}

    try:
        if float(input_dict.get('heart_rate', 0)) < 0:
            return {"error": "heart_rate cannot be negative"}
    except (ValueError, TypeError):
        return {"error": "heart_rate must be a number"}

    # STEP 3 — Convert dict to DataFrame
    try:
        input_df = pd.DataFrame([input_dict])
        input_df['activity_type'] = activity_enc.transform(input_df['activity_type'])
        input_df = input_df[feature_cols]
    except Exception as e:
        return {"error": f"Data preparation failed: {str(e)}"}

    # STEP 4 — Scale and Predict
    try:
        X_scaled       = scaler.transform(input_df)
        pred_encoded   = model.predict(X_scaled)[0]
        pred_proba     = model.predict_proba(X_scaled)[0]
        confidence_pct = round(max(pred_proba) * 100, 1)
    except Exception as e:
        return {"error": f"Prediction failed: {str(e)}"}

    # STEP 5 — Return clean dict
    prediction_label = label_enc.inverse_transform([pred_encoded])[0]

    return {
        "prediction"  : prediction_label,
        "confidence"  : f"{confidence_pct}%",
        "top_features": top_features,
        "risk_level"  : prediction_label
    }

print("✅ predict() function is ready!")

test_cases = [
    # GROUP A — Normal Cases (3)
    {"label": "Case 1 — Normal walking",
     "input": {'heart_rate':72,'spo2_level':98.5,'ecg_signal':0.05,
               'respiration_rate':15,'body_temperature':36.6,
               'blood_pressure_sys':118,'blood_pressure_dia':78,
               'blood_glucose':95.0,'eeg_alpha_power':10.0,
               'eeg_beta_power':6.5,'emg_signal_strength':0.5,
               'fall_detected':0,'step_count':1200,
               'ambient_temperature':27.0,'stress_level_index':30,
               'activity_type':'walking'}, "expected":"Low"},

    {"label": "Case 2 — Normal sleeping",
     "input": {'heart_rate':60,'spo2_level':97.8,'ecg_signal':-0.02,
               'respiration_rate':12,'body_temperature':36.2,
               'blood_pressure_sys':112,'blood_pressure_dia':72,
               'blood_glucose':88.0,'eeg_alpha_power':11.5,
               'eeg_beta_power':5.2,'emg_signal_strength':0.3,
               'fall_detected':0,'step_count':50,
               'ambient_temperature':24.0,'stress_level_index':15,
               'activity_type':'sleeping'}, "expected":"Low"},

    {"label": "Case 3 — Normal resting",
     "input": {'heart_rate':68,'spo2_level':99.0,'ecg_signal':0.01,
               'respiration_rate':14,'body_temperature':36.5,
               'blood_pressure_sys':120,'blood_pressure_dia':80,
               'blood_glucose':105.0,'eeg_alpha_power':9.8,
               'eeg_beta_power':7.1,'emg_signal_strength':0.45,
               'fall_detected':0,'step_count':200,
               'ambient_temperature':26.0,'stress_level_index':25,
               'activity_type':'resting'}, "expected":"Low"},

    # GROUP B — High Risk Cases (2)
    {"label": "Case 4 — High Risk (high BP + low SpO2)",
     "input": {'heart_rate':115,'spo2_level':90.5,'ecg_signal':0.85,
               'respiration_rate':24,'body_temperature':38.8,
               'blood_pressure_sys':175,'blood_pressure_dia':105,
               'blood_glucose':210.0,'eeg_alpha_power':7.2,
               'eeg_beta_power':9.8,'emg_signal_strength':0.9,
               'fall_detected':1,'step_count':50,
               'ambient_temperature':38.0,'stress_level_index':90,
               'activity_type':'resting'}, "expected":"High"},

    {"label": "Case 5 — High Risk (fall + tachycardia)",
     "input": {'heart_rate':130,'spo2_level':91.0,'ecg_signal':1.2,
               'respiration_rate':26,'body_temperature':39.1,
               'blood_pressure_sys':160,'blood_pressure_dia':100,
               'blood_glucose':250.0,'eeg_alpha_power':6.5,
               'eeg_beta_power':11.0,'emg_signal_strength':0.95,
               'fall_detected':1,'step_count':20,
               'ambient_temperature':40.0,'stress_level_index':95,
               'activity_type':'running'}, "expected":"High"},

    # GROUP C — Edge Cases (2)
    {"label": "Case 6 — Edge (minimum values)",
     "input": {'heart_rate':40,'spo2_level':85.0,'ecg_signal':-2.0,
               'respiration_rate':8,'body_temperature':34.0,
               'blood_pressure_sys':80,'blood_pressure_dia':50,
               'blood_glucose':50.0,'eeg_alpha_power':1.0,
               'eeg_beta_power':1.0,'emg_signal_strength':0.01,
               'fall_detected':0,'step_count':0,
               'ambient_temperature':10.0,'stress_level_index':1,
               'activity_type':'sleeping'}, "expected":"High"},

    {"label": "Case 7 — Edge (maximum values)",
     "input": {'heart_rate':200,'spo2_level':100.0,'ecg_signal':2.0,
               'respiration_rate':35,'body_temperature':42.0,
               'blood_pressure_sys':220,'blood_pressure_dia':130,
               'blood_glucose':400.0,'eeg_alpha_power':25.0,
               'eeg_beta_power':25.0,'emg_signal_strength':1.0,
               'fall_detected':1,'step_count':10000,
               'ambient_temperature':55.0,'stress_level_index':100,
               'activity_type':'running'}, "expected":"High"},

    # GROUP D — Known Dataset Rows (2)
    {"label": "Case 8 — Dataset row (walking, low stress)",
     "input": {'heart_rate':62,'spo2_level':98.4,'ecg_signal':-0.001,
               'respiration_rate':14,'body_temperature':36.2,
               'blood_pressure_sys':125,'blood_pressure_dia':86,
               'blood_glucose':117.5,'eeg_alpha_power':9.7,
               'eeg_beta_power':7.63,'emg_signal_strength':0.59,
               'fall_detected':0,'step_count':1497,
               'ambient_temperature':25.2,'stress_level_index':48,
               'activity_type':'walking'}, "expected":"Low"},

    {"label": "Case 9 — Dataset row (sleeping, fall detected)",
     "input": {'heart_rate':82,'spo2_level':92.2,'ecg_signal':0.4,
               'respiration_rate':14,'body_temperature':37.0,
               'blood_pressure_sys':115,'blood_pressure_dia':82,
               'blood_glucose':162.3,'eeg_alpha_power':7.32,
               'eeg_beta_power':6.77,'emg_signal_strength':0.22,
               'fall_detected':1,'step_count':960,
               'ambient_temperature':27.7,'stress_level_index':46,
               'activity_type':'sleeping'}, "expected":"Medium"},

    # GROUP E — Invalid Input (1)
    {"label": "Case 10 — INVALID (negative heart_rate)",
     "input": {'heart_rate':-5,'spo2_level':97.0,'ecg_signal':0.05,
               'respiration_rate':15,'body_temperature':36.5,
               'blood_pressure_sys':120,'blood_pressure_dia':80,
               'blood_glucose':100.0,'eeg_alpha_power':10.0,
               'eeg_beta_power':6.5,'emg_signal_strength':0.5,
               'fall_detected':0,'step_count':500,
               'ambient_temperature':27.0,'stress_level_index':30,
               'activity_type':'walking'}, "expected":"ERROR"},
]

print(f"✅ {len(test_cases)} test cases ready")

results = []

for tc in test_cases:
    result = predict(tc["input"])

    if "error" in result:
        pred   = "Error"
        conf   = "N/A"
        status = "ERROR (caught ✅)" if tc["expected"] == "ERROR" else "FAIL ❌"
    else:
        pred   = result["prediction"]
        conf   = result["confidence"]
        exp    = tc["expected"]
        status = "PASS ✅" if pred == exp else f"FAIL ❌ (expected {exp})"

    results.append({
        "Test Case"  : tc["label"],
        "Prediction" : pred,
        "Confidence" : conf,
        "Status"     : status
    })

results_df = pd.DataFrame(results)
print("\n" + "="*75)
print("TASK 3 — RESULTS TABLE")
print("="*75)
print(results_df.to_string(index=False))
print("="*75)

passed = sum(1 for r in results if "PASS" in r["Status"])
errors = sum(1 for r in results if "ERROR" in r["Status"])
print(f"\n✅ {passed} PASS  |  ⚠️ {errors} ERROR (invalid input correctly caught)")

print(f"""
╔══════════════════════════════════════════════════════════╗
║        MODEL SUMMARY CARD — Track 3                     ║
║        Heart Rate & Vitals Risk Predictor                ║
╚══════════════════════════════════════════════════════════╝

[Section 1] Project & Domain
  Project : Heart Rate & Vitals Risk Predictor
  Domain  : Healthcare / Remote Patient Monitoring
  Track   : 3

[Section 2] Algorithm & Tuning
  Algorithm : Random Forest Classifier
  Tuning    : n_estimators=200, max_depth=12,
              min_samples_split=4, class_weight=balanced

[Section 3] Dataset
  File    : HeartRate_Cleaned.csv
  Rows    : 670 patient records
  Target  : risk_level → Low / Medium / High

[Section 4] Final Metric Scores
  Accuracy  : {acc:.1%}
  F1-Score  : {f1:.3f}
  CV Mean   : {cv.mean():.3f} ± {cv.std():.3f}

[Section 5] PKL Files
  final_model.pkl       → RandomForestClassifier
  scaler.pkl            → StandardScaler
  label_encoder.pkl     → Low / Medium / High
  activity_encoder.pkl  → walking/running/resting/sleeping
  feature_columns.pkl   → 16 ordered input column names
  top_features.pkl      → Top 3 important features

[Section 6] Sample Input
  {{
    'heart_rate'        : 72,
    'spo2_level'        : 98.5,
    'ecg_signal'        : 0.05,
    'respiration_rate'  : 15,
    'body_temperature'  : 36.6,
    'blood_pressure_sys': 118,
    'blood_pressure_dia': 78,
    'blood_glucose'     : 95.0,
    'eeg_alpha_power'   : 10.0,
    'eeg_beta_power'    : 6.5,
    'emg_signal_strength': 0.5,
    'fall_detected'     : 0,
    'step_count'        : 1200,
    'ambient_temperature': 27.0,
    'stress_level_index': 30,
    'activity_type'     : 'walking'
  }}

[Section 7] Sample Output
  {{
    'prediction'  : 'Low',
    'confidence'  : '91.3%',
    'top_features': {TOP_FEATURES},
    'risk_level'  : 'Low'
  }}
""")

import zipfile
from google.colab import files

with zipfile.ZipFile("Track3_models.zip", 'w') as zf:
    for f in os.listdir("models"):
        zf.write(f"models/{f}", f)

print("✅ ZIP created with all PKL files")
files.download("Track3_models.zip")
print("📥 Download started! Give this ZIP to the Flask team.")